# Generated by Django 4.0.4 on 2022-05-15 20:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='blog_content',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
