# Generated by Django 4.0.4 on 2022-05-22 04:06

from django.db import migrations, models
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bloglistingpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingpage',
            name='content',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add title', requiered=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(requiered=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, requiered=True)), ('text', wagtail.core.blocks.TextBlock(max_length=80, requiered=True)), ('button_card', wagtail.core.blocks.PageChooserBlock(requiered=False)), ('button_url', wagtail.core.blocks.URLBlock(requiered=False))])))])), ('full_rich_text', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloglistingpage',
            name='custom_title',
            field=models.CharField(help_text='Titulo del blog', max_length=100),
        ),
    ]
