# Generated by Django 4.0.4 on 2022-05-18 16:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0003_homepage_canonical_url_homepage_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='Paint Ball Park - Santa Cruz', max_length=30, null=True, verbose_name='titulo H1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='effects_image',
            field=models.BooleanField(default=True, help_text='Efecto imagen Aro', verbose_name='Efectos Imagenes'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='effects_text',
            field=models.BooleanField(default=True, help_text='Efectos de texto', verbose_name='Efectos Texto'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='repeat',
            field=models.BooleanField(default=False, help_text='Repite indefinidamente', verbose_name='Repetición'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slideTime',
            field=models.IntegerField(default=4000, help_text='Tiempo en milisegundos', verbose_name='Tiempo'),
        ),
        migrations.CreateModel(
            name='HomePageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
