# Generated by Django 4.0.4 on 2022-05-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_banner_title_homepage_effects_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='effects_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='effects_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slideTime',
        ),
    ]
