# Generated by Django 4.0.4 on 2022-05-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('c_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='facebook page', null=True)),
                ('instagram', models.URLField(blank=True, help_text='instagram', null=True)),
                ('youtube', models.URLField(blank=True, help_text='youtube channel', null=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Telefono whtasapp +591xxxxxxxx', max_length=12, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
