# Generated by Django 4.0.4 on 2022-05-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0006_alter_svg_file'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('c_settings', '0003_analyticssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon', to='wagtailimages.image', verbose_name='Favicon PNG')),
                ('logo', models.ForeignKey(blank=True, help_text="SVG File example.... <svg class='w-8 h-8' xmlns='http://www.w3.org/2000/svg'    version='1.1' viewBox='0 0 350 350'>   <g transform='translate(-258.272 -38.53)'>  <path fill='currentColor' d='m342.425 ...' />    </g> </svg>", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Logo SVG')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
