# Generated by Django 4.0.4 on 2022-05-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
