# Generated by Django 4.0.4 on 2022-05-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscriptor', 'verbose_name_plural': 'Subscriptores'},
        ),
    ]
